const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamailblock.com', 'grr.la',
  'sharklasers.com', 'guerrillamailblock.com', 'spam4.me', 'trashmail.com',
  'trashmail.at', 'trashmail.io', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'yopmail.com', 'yopmail.fr', 'cool.fr.nf', 'jetable.fr.nf', 'nospam.ze.tc',
  'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr', 'courriel.fr.nf', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf', 'tempmail.com', 'temp-mail.org', 'tempmail.net',
  'tempmail.ninja', 'tempr.email', 'dispostable.com', 'throwam.com', 'throwam.net',
  'throwaway.email', 'mailnull.com', 'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'mailnesia.com', 'mailnull.com', 'spamfree24.org',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamfree.eu', 'binkmail.com', 'bob-email.com', 'imgof.com', 'jnxjn.com',
  'MailNull.com', 'spampoison.com', 'spaml.de', 'spaml.com', 'spaml.net',
  'spamspot.com', 'spamthis.co.uk', 'spamthisplease.com', 'filzmail.com',
  'throwam.com', 'getairmail.com', 'filzmail.com', 'discard.email',
  'discardmail.com', 'discardmail.de', 'spamgrap.de', 'anonbox.net',
  'anonymbox.com', 'antispam.de', 'deadaddress.com', 'despam.it',
  'dispostable.com', 'dodgit.com', 'dumpmail.de', 'e4ward.com',
  'emailias.com', 'emailsensei.com', 'emailtemporario.com.br', 'emailthe.net',
  'emailtmp.com', 'emailwarden.com', 'fakeinbox.com', 'fakeinformation.com',
  'fastacura.com', 'fastchevy.com', 'fastchrysler.com', 'fastkia.com',
  'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com',
  'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com', 'filzmail.com',
  'fizmail.com', 'frontflip.com', 'fux0ringduh.com', 'garliclife.com',
  'get1mail.com', 'getonemail.net', 'girlsundertheinfluence.com', 'gishpuppy.com',
  'gonuts4free.com', 'gowikibooks.com', 'gowikicampus.com', 'gowikifilms.com',
  'gowikigames.com', 'gowikimusic.com', 'gowikinetwork.com', 'gowikitravel.com',
  'gowikitv.com', 'grandmamail.com', 'grandmasmail.com', 'h.mintemail.com',
  'h8s.org', 'haltospam.com', 'hatespam.org', 'herp.in', 'hidemail.de',
  'hidzz.com', 'hmamail.com', 'hochsitze.com', 'hopemail.biz', 'hulapla.de',
  'ieatspam.eu', 'ieatspam.info', 'ihateyoualot.info', 'iheartspam.org',
  'ikbenspamvrij.nl', 'imails.info', 'inoutmail.de', 'inoutmail.eu',
  'inoutmail.info', 'inoutmail.net', 'internet-e-mail.de', 'internet-mail.de',
  'internetemails.net', 'internetmailing.net', 'isosq.com', 'jetable.com',
  'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com', 'jsrsolutions.com',
  'junk1.tk', 'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net',
  'klzlk.com', 'koszmail.pl', 'kurzepost.de', 'letthemeatspam.com',
  'lhsdv.com', 'lifebyfood.com', 'link2mail.net', 'litedrop.com', 'lol.ovpn.to',
  'lookugly.com', 'lortemail.dk', 'lr78.com', 'lroid.com', 'lukop.dk',
  'm21.cc', 'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net', 'mail2rss.org',
  'mailbidon.com', 'mailbiz.biz', 'mailblocks.com', 'mailbucket.org',
  'mailc.net', 'mailcat.biz', 'mailcatch.com', 'mailde.de', 'mailde.info',
  'maildrop.cc', 'maileimer.de', 'mailexpire.com', 'mailf5.com', 'mailfall.com',
  'mailfree44.com', 'mailfreeonline.com', 'mailguard.me', 'mailhz.me',
  'mailin8r.com', 'mailinater.com', 'mailismagic.com', 'mailme.ir',
  'mailme.lv', 'mailme24.com', 'mailmetrash.com', 'mailmoat.com',
  'mailms.com', 'mailnew.com', 'mailnull.com', 'mailorg.org', 'mailpick.biz',
  'mailrock.biz', 'mailscrap.com', 'mailseal.de', 'mailshell.com',
  'mailsiphon.com', 'mailslite.com', 'mailtemp.info', 'mailtome.de',
  'mailtothis.com', 'mailtrash.net', 'mailtv.net', 'mailtv.tv',
  'mailzilla.com', 'makemetheking.com', 'manybrain.com', 'mbx.cc',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com',
  'mt2009.com', 'mt2014.com', 'mt2015.com', 'mycard.net.ua', 'mycleaninbox.net',
  'mypartyclip.de', 'myphantomemail.com', 'myspaceinc.com', 'myspaceinc.net',
  'myspaceinc.org', 'myspacepimpedup.com', 'myspamless.com', 'mytrashmail.com',
  'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net', 'netmails.com',
  'netmails.net', 'nevermail.de', 'nfast.net', 'no-spam.ws', 'noblepioneer.com',
  'nogmailspam.info', 'nomorespamemails.com', 'nonspam.eu', 'nonspammer.de',
  'noref.in', 'norseforce.com', 'nospam.ze.tc', 'nospam4.us', 'nospamfor.us',
  'nospammail.net', 'nospamthanks.info', 'notmailinator.com', 'nowmymail.com',
  'ntlhelp.net', 'nullbox.info', 'objectmail.com', 'obobbo.com', 'odnorazovoe.ru',
  'oneoffemail.com', 'onewaymail.com', 'online.ms', 'oopi.org', 'opayq.com',
  'ordinaryamerican.net', 'otherinbox.com', 'owlpic.com', 'pancakemail.com',
  'paplease.com', 'pepbot.com', 'pfui.ru', 'pjjkp.com', 'plexolan.de',
  'poczta.onet.pl', 'politikerclub.de', 'poofy.org', 'pookmail.com',
  'privacy.net', 'privatdemail.net', 'proxymail.eu', 'prtnx.com', 'punkass.com',
  'put2.net', 'putthisinyourspamdatabase.com', 'qq.com', 'recode.me',
  'recursor.net', 'regbypass.com', 'rejectmail.com', 'rklips.com',
  'rmqkr.net', 'royal.net', 'rppkn.com', 'rtrtr.com', 's0ny.net',
  'safe-mail.net', 'safetymail.info', 'safetypost.de', 'sandelf.de',
  'schafmail.de', 'schrott-email.de', 'secretmail.net', 'secure-mail.biz',
  'senseless-entertainment.com', 'sharklasers.com', 'shieldedmail.com',
  'shitmail.de', 'shitmail.me', 'shitmail.org', 'shortmail.net',
  'sibmail.com', 'skeefmail.com', 'slapsfromlastnight.com', 'slippery.email',
  'slopsbox.com', 'smellfear.com', 'smwg.info', 'snakemail.com', 'sneakemail.com',
  'sneakmail.de', 'snkmail.com', 'sofimail.com', 'sofort-mail.de', 'sogetthis.com',
  'soodonims.com', 'spam.la', 'spam.su', 'spam4.me', 'spamail.de',
  'spambob.com', 'spambob.net', 'spambob.org', 'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamdecoy.net', 'spamex.com',
  'spamfree24.org', 'spamgoes.in', 'spamgrap.de', 'spamherelots.com',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info', 'spaml.com', 'spammotel.com',
  'spamobox.com', 'spamoff.de', 'spamsalad.in', 'spamsphere.com',
  'spamspot.com', 'spamthis.co.uk', 'spamtroll.net', 'speed.1s.fr',
  'spoofmail.de', 'stuffmail.de', 'super-auswahl.de', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info',
  'tafmail.com', 'tagyourself.com', 'teewars.org', 'teleworm.com',
  'teleworm.us', 'temp-mail.ru', 'temp.emeraldwebmail.com', 'temp.headstrong.de',
  'tempail.com', 'tempalias.com', 'tempemail.biz', 'tempemail.com',
  'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail.it',
  'tempmail2.com', 'tempmaildemo.com', 'tempmailer.com', 'tempmailer.de',
  'tempomail.fr', 'temporaryemail.net', 'temporaryemail.us', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymailaddress.com', 'tempthe.net', 'thankyou2010.com',
  'thecloudindex.com', 'thisisnotmyrealemail.com', 'throam.com', 'throwam.com',
  'throwaway.email', 'throwam.net', 'tilien.com', 'tittbit.in', 'tizi.com',
  'tmail.com', 'tmail.io', 'tmailinator.com', 'toiea.com', 'toomail.biz',
  'topranklist.de', 'tradermail.info', 'trash-amil.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de', 'trash-mail.ga', 'trash-mail.io',
  'trash-mail.net', 'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashdevil.com', 'trashdevil.de', 'trashemail.de', 'trashimail.com',
  'trashmail.at', 'trashmail.com', 'trashmail.io', 'trashmail.me',
  'trashmail.net', 'trashmail.org', 'trashmail.xyz', 'trashmailer.com',
  'trashmailer.me', 'trashmailer.net', 'trashmailer.org', 'trashmailgenerator.de',
  'trbvm.com', 'trillianpro.com', 'trnwx.com', 'trskye.com', 'twinmail.de',
  'tyldd.com', 'uggsrock.com', 'umail.net', 'uroid.com', 'us.af',
  'veryrealemail.com', 'viditag.com', 'vipmail.name', 'vipmail.pw',
  'webm4il.info', 'wegwerfadresse.de', 'wegwerfemail.de', 'wegwerfmail.de',
  'wegwerfmail.net', 'wegwerfmail.org', 'wetrainbayarea.com', 'wetrainbayarea.org',
  'wh4f.org', 'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com',
  'wilemail.com', 'wuzupmail.net', 'www.e4ward.com', 'www.gishpuppy.com',
  'www.mailinator.com', 'wwwnew.eu', 'xagloo.co', 'xagloo.com',
  'xemaps.com', 'xents.com', 'xmaily.com', 'xoxy.net', 'xyzfree.net',
  'yapped.net', 'yeah.net', 'yep.it', 'yogamaven.com', 'yopmail.com',
  'yopmail.fr', 'yopmail.pp.ua', 'youmail.ga', 'ypmail.webarnak.fr.eu.org',
  'yuurok.com', 'z1p.biz', 'za.com', 'zebins.com', 'zebins.eu',
  'zehnminuten.de', 'zippymail.info', 'zoemail.net', 'zoemail.org',
  'zomg.info', 'zxcv.com', 'zxcvbnm.com', 'zzz.com',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return false
  return DISPOSABLE_DOMAINS.has(domain)
}
